.PHONY: clean All

All:
	@echo "----------Building project:[ Day_one_ - Debug ]----------"
	@cd "Day_one_" && "$(MAKE)" -f  "Day_one_.mk"
clean:
	@echo "----------Cleaning project:[ Day_one_ - Debug ]----------"
	@cd "Day_one_" && "$(MAKE)" -f  "Day_one_.mk" clean
